"""Weak supervision: keyword + emotion heuristic for MDCC.

Rationale: MDCC ships without manipulation labels (no public manipulation-labelled
crowdfunding dataset exists). Manually annotating 14,961 campaigns is impractical
for coursework scope. We therefore use *weak supervision* — labels generated by a
documented, reproducible heuristic — and clearly disclose this in the report's
Methodology and Limitations.

The heuristic is intentionally simple and transparent:
  • A lexicon of manipulation-cue terms covering four categories:
      - sympathy_exploitation (e.g. "innocent", "helpless")
      - artificial_urgency    (e.g. "urgent", "immediately", "running out of time")
      - guilt_framing         (e.g. "would not be able to live with", "your fault")
      - fear_appeal           (e.g. "die", "lose everything", "hopeless")
  • A density score = (# manipulation-cue matches) / (# tokens, normalised by log).
  • Optionally combine with GoEmotions-derived emotion intensities if available.

The label is the *category with the highest density score* if any score exceeds a
threshold; otherwise non_manipulative. For binary labels, we collapse all four
manipulation categories into "manipulative".

KNOWN LIMITATIONS (acknowledged in the report):
  - Lexicon-based labels are noisy; they tag emotional appeals even when genuine.
  - Threshold is set empirically; not learned.
  - Manipulation is contextual; a single phrase doesn't always indicate intent.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Iterable

import pandas as pd

from src import config


# ---------------------------------------------------------------------------
# Lexicons. Kept short and unambiguous; each phrase is intentionally a strong
# cue. We use word-boundary regex so partial matches don't fire spuriously.
# ---------------------------------------------------------------------------
SYMPATHY_LEXICON = [
    r"innocent", r"helpless", r"poor (?:little|young|sweet|baby)",
    r"breaks? (?:my|our|your) heart", r"heartbreaking", r"vulnerable",
    r"defen[sc]eless", r"struggling alone", r"all alone",
    r"abandoned", r"only family", r"left with nothing",
    r"begging", r"plea(?:d|s|se help)", r"desperate",
]

URGENCY_LEXICON = [
    r"urgent(?:ly)?", r"immediately", r"right now", r"asap",
    r"running out of time", r"out of time", r"only days?(?: left)?",
    r"only hours?(?: left)?", r"deadline", r"before it'?s too late",
    r"time is running out", r"every (?:second|minute|hour) counts",
    r"last chance", r"can'?t wait", r"won'?t survive without",
]

GUILT_LEXICON = [
    r"could not live with (?:my|our|your)?\s*self",
    r"on (?:my|our|your) conscience",
    r"please don'?t (?:turn|look) away",
    r"if you don'?t help", r"if no one helps",
    r"how can you ignore", r"shame", r"failed (?:my|our|him|her|them)",
    r"i'?m sorry to ask", r"begging for help",
    r"selfish to (?:ignore|walk past)", r"can you live with",
]

FEAR_LEXICON = [
    r"(?:she|he|they|we) (?:will|could) die",
    r"lose (?:my|our|her|his|their) (?:life|home|everything)",
    r"hopeless", r"no hope", r"terrified", r"horrifying",
    r"nightmare", r"can'?t breathe", r"organ(?:s)? failing",
    r"death(?:bed)?", r"funeral", r"buried alive",
    r"won'?t make it", r"running out of options", r"no other choice",
]

CATEGORY_LEXICONS = {
    "sympathy_exploitation": SYMPATHY_LEXICON,
    "artificial_urgency":    URGENCY_LEXICON,
    "guilt_framing":         GUILT_LEXICON,
    "fear_appeal":           FEAR_LEXICON,
}

# Density threshold above which a category is considered "fired".
# Calibrated to flag roughly the top ~25–35% of campaigns as manipulative,
# which is the typical class balance reported in persuasion / manipulation
# literature (Mitra & Gilbert 2014 found ~30–40% of Kickstarter campaigns
# use heightened persuasive language).
DENSITY_THRESHOLD = 0.015


@dataclass
class WeakLabelResult:
    binary_label: str       # "manipulative" or "non_manipulative"
    fine_label: str         # one of LABELS_4CLASS
    scores: dict[str, float]


def _compile_lexicons():
    """Compile regex patterns once for speed."""
    import re
    return {
        cat: [re.compile(rf"\b{pat}\b", re.IGNORECASE) for pat in pats]
        for cat, pats in CATEGORY_LEXICONS.items()
    }


_COMPILED = _compile_lexicons()


def score_text(text: str) -> WeakLabelResult:
    """Compute per-category densities and pick a label."""
    n_tokens = max(1, len(text.split()))
    log_norm = math.log1p(n_tokens)  # log(1+n) damps long-document advantage
    scores: dict[str, float] = {}
    for cat, patterns in _COMPILED.items():
        hits = sum(len(p.findall(text)) for p in patterns)
        scores[cat] = hits / log_norm

    top_cat, top_score = max(scores.items(), key=lambda kv: kv[1])
    if top_score < DENSITY_THRESHOLD:
        return WeakLabelResult("non_manipulative", "non_manipulative", scores)

    # Merge guilt + fear into one fine class because their lexicons overlap and
    # the literature treats them under "negative-affect manipulation". Keeps
    # the 4-class label set well-separated.
    fine = "guilt_or_fear" if top_cat in ("guilt_framing", "fear_appeal") else top_cat
    return WeakLabelResult("manipulative", fine, scores)


def label_dataframe(df: pd.DataFrame, text_col: str = "text") -> pd.DataFrame:
    """Add binary_label, fine_label, and per-category score columns to df."""
    out = df.copy()
    results = [score_text(t) for t in out[text_col].fillna("")]
    out["binary_label"] = [r.binary_label for r in results]
    out["fine_label"] = [r.fine_label for r in results]
    for cat in CATEGORY_LEXICONS:
        out[f"score_{cat}"] = [r.scores[cat] for r in results]
    return out
